name: On pre-release creation
run-name: Pre-release ${{ github.event.release.tag_name }}

on:
  release:
    types: [prereleased]

jobs:
  release-module:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-release-module.yml@v2
    secrets: inherit
    with:
      skip_staging: false
